defmodule Campfire.Schema.TimestampTest do
  use Campfire.DataCase, async: true

  alias Campfire.Accounts.{Session, User}
  alias Campfire.Messages.Message
  alias Campfire.Schema.Timestamp

  test "formats like Rails: fraction only when microseconds aren't zero" do
    assert Timestamp.format(~U[2026-03-02 15:55:00Z]) == "2026-03-02 15:55:00"
    assert Timestamp.format(~U[2026-03-02 15:55:00.000000Z]) == "2026-03-02 15:55:00"
    assert Timestamp.format(~U[2026-03-02 15:55:00.120000Z]) == "2026-03-02 15:55:00.120000"
    assert Timestamp.format(~U[2026-03-02 15:55:00.000001Z]) == "2026-03-02 15:55:00.000001"
  end

  test "loads every variant found in the database" do
    for {text, expected} <- [
          {"2026-03-02 15:55:00", ~U[2026-03-02 15:55:00.000000Z]},
          {"2026-03-02 15:55:00.123", ~U[2026-03-02 15:55:00.123000Z]},
          {"2026-03-02 15:55:00.123456", ~U[2026-03-02 15:55:00.123456Z]},
          {"2026-03-02T15:55:00Z", ~U[2026-03-02 15:55:00.000000Z]}
        ] do
      assert Timestamp.load(text) == {:ok, expected}
    end
  end

  test "round-trips seed rows byte for byte" do
    %{rows: rows} = Repo.query!("SELECT id, created_at, updated_at FROM messages")

    for [id, created_at, updated_at] <- rows do
      message = Repo.get!(Message, id)
      assert Timestamp.format(message.created_at) == created_at
      assert Timestamp.format(message.updated_at) == updated_at
    end
  end

  test "writes and binds Rails' text format" do
    user = Repo.get_by!(User, email_address: label("emails.david"))
    now = ~U[2026-10-05 12:00:00.250000Z]

    session =
      Repo.insert!(%Session{
        user_id: user.id,
        token: "t",
        last_active_at: now,
        created_at: now,
        updated_at: now
      })

    %{rows: [[text]]} =
      Repo.query!("SELECT last_active_at FROM sessions WHERE id = ?", [session.id])

    assert text == "2026-10-05 12:00:00.250000"

    # Comparisons happen on the text, so bound parameters must use the same format.
    assert Repo.exists?(
             from s in Session,
               where: s.id == ^session.id and s.created_at > ^~U[2026-10-05 12:00:00Z]
           )

    refute Repo.exists?(from s in Session, where: s.id == ^session.id and s.created_at > ^now)
  end

  test "autogenerated timestamps carry microseconds" do
    user = Repo.get_by!(User, email_address: label("emails.david"))

    session =
      Repo.insert!(%Session{user_id: user.id, token: "t2", last_active_at: Timestamp.utc_now()})

    assert {_, 6} = session.created_at.microsecond
  end
end
