defmodule Campfire.SigningTest do
  # Vectors generated by Rails with the bench SECRET_KEY_BASE (docs/SPEC.md §3, labels.json).
  use ExUnit.Case, async: true

  import Campfire.DataCase, only: [label: 1]
  alias Campfire.Signing
  alias Jason.OrderedObject

  @avatar_1 "eyJfcmFpbHMiOnsiZGF0YSI6MSwicHVyIjoidXNlci9hdmF0YXIifX0--023b16424a00933214f527b2dbc6cb54ffa966a5b4fa3375c0678891f4e168e1"

  test "avatar tokens are Rails signed ids" do
    assert Signing.signed_id(1, "user/avatar") == @avatar_1
    assert Signing.verify_signed_id(@avatar_1, "user/avatar") == {:ok, 1}

    for {name, id} <- [{"jason", 149_087_659}, {"david", 127_326_141}] do
      token = label("avatar_tokens.#{name}")
      assert Signing.verify_signed_id(token, "user/avatar") == {:ok, id}
      assert Signing.signed_id(id, "user/avatar") == token
    end
  end

  test "tampered, truncated or repurposed tokens don't verify" do
    assert Signing.verify_signed_id(@avatar_1, "user/other") == :error

    assert Signing.verify_signed_id(String.replace(@avatar_1, "--0", "--1"), "user/avatar") ==
             :error

    assert Signing.verify_signed_id("eyJf--abc", "user/avatar") == :error
    assert Signing.verify_signed_id("", "user/avatar") == :error
  end

  test "Turbo signed stream names" do
    rooms = "InJvb21zIg==--60a2ff565fb2226042c779b5711156db1d1cc48f89e6f59c94e4bf1da3f0945c"
    assert Signing.signed_stream_name("rooms") == rooms
    assert Signing.verify_stream_name(rooms) == {:ok, "rooms"}

    name = Signing.gid_param("Rooms::Open", 1) <> ":messages"
    assert name == "Z2lkOi8vY2FtcGZpcmUvUm9vbXM6Ok9wZW4vMQ:messages"

    assert Signing.signed_stream_name(name) ==
             "IloybGtPaTh2WTJGdGNHWnBjbVV2VW05dmJYTTZPazl3Wlc0dk1ROm1lc3NhZ2VzIg==--6ff497f9ec2f68f7ec64a5aee2fe25bd5ca8e2647ff82db8e211aabd83382b8b"
  end

  test "signed global ids for mentions" do
    assert Signing.sgid("User", 1) ==
             "eyJfcmFpbHMiOnsiZGF0YSI6ImdpZDovL2NhbXBmaXJlL1VzZXIvMT9leHBpcmVzX2luIiwicHVyIjoiYXR0YWNoYWJsZSJ9fQ==--f7d8e8773314d3310320f3cdd08e5597bb51ca1a"
  end

  test "Active Storage messages via the primitives" do
    assert 42 |> Signing.envelope("blob_id") |> Signing.sign("ActiveStorage", :sha, :strict) ==
             "eyJfcmFpbHMiOnsiZGF0YSI6NDIsInB1ciI6ImJsb2JfaWQifX0=--c252dc1b14dd0e8cd599eb40203378880bafed1f"

    variation = OrderedObject.new([{"format", "jpg"}, {"resize_to_limit", [1200, 800]}])

    signed =
      variation |> Signing.envelope("variation") |> Signing.sign("ActiveStorage", :sha, :strict)

    assert signed ==
             "eyJfcmFpbHMiOnsiZGF0YSI6eyJmb3JtYXQiOiJqcGciLCJyZXNpemVfdG9fbGltaXQiOlsxMjAwLDgwMF19LCJwdXIiOiJ2YXJpYXRpb24ifX0=--28426ca1e33b0fea71b8b10b7f52a844de5886cf"

    assert {:ok, json} = Signing.verify(signed, "ActiveStorage", :sha, :strict)

    assert Signing.open_envelope(json, "variation") ==
             {:ok, %{"format" => "jpg", "resize_to_limit" => [1200, 800]}}
  end

  test "expiring envelopes" do
    past = Signing.envelope(1, "p", ~U[2020-01-01 00:00:00Z])
    assert past =~ ~s("exp":"2020-01-01T00:00:00.000Z")
    assert Signing.open_envelope(past, "p") == :error

    assert Signing.open_envelope(Signing.envelope(1, "p", ~U[2046-01-01 00:00:00Z]), "p") ==
             {:ok, 1}
  end
end
